[2024-10-09 08:36:59,713] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.query_contract 2024-10-09T08:36:58.530644+00:00 [queued]>
[2024-10-09 08:36:59,721] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.query_contract 2024-10-09T08:36:58.530644+00:00 [queued]>
[2024-10-09 08:36:59,722] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 08:36:59,728] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-10-09 08:36:59,732] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 08:36:59,744] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): query_contract> on 2024-10-09T08:36:58.530644+00:00
[2024-10-09 08:36:59,748] {standard_task_runner.py:52} INFO - Started process 84158 to run task
[2024-10-09 08:36:59,750] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mssql_dag', 'query_contract', '2024-10-09T08:36:58.530644+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mssql_dag.py', '--cfg-path', '/tmp/tmp562i90uj', '--error-file', '/tmp/tmp4kv4jzro']
[2024-10-09 08:36:59,754] {standard_task_runner.py:77} INFO - Job 9: Subtask query_contract
[2024-10-09 08:36:59,789] {logging_mixin.py:104} INFO - Running <TaskInstance: mssql_dag.query_contract 2024-10-09T08:36:58.530644+00:00 [running]> on host da843a407010
[2024-10-09 08:36:59,873] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mssql_dag
AIRFLOW_CTX_TASK_ID=query_contract
AIRFLOW_CTX_EXECUTION_DATE=2024-10-09T08:36:58.530644+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-09T08:36:58.530644+00:00
[2024-10-09 08:36:59,929] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 447, in pymssql._pymssql.Cursor.execute
  File "src/pymssql/_mssql.pyx", line 1125, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1156, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1289, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src/pymssql/_mssql.pyx", line 1852, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1898, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (1038, b'An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 1681, in execute
    cur.execute(*args, **kwargs)
  File "src/pymssql/_pymssql.pyx", line 465, in pymssql._pymssql.Cursor.execute
pymssql.exceptions.OperationalError: (1038, b'An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mssql_dag.py", line 35, in query_table
    df = pd.read_sql(query, connection)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 489, in read_sql
    chunksize=chunksize,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 1727, in read_query
    cursor = self.execute(*args)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 1693, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'SELECT * FROM Empty DataFrame
Columns: []
Index: []': (1038, b'An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n')
[2024-10-09 08:36:59,942] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=mssql_dag, task_id=query_contract, execution_date=20241009T083658, start_date=20241009T083659, end_date=20241009T083659
[2024-10-09 08:36:59,963] {local_task_job.py:149} INFO - Task exited with return code 1
