[2024-10-10 02:17:20,464] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.query_contract 2024-10-10T02:17:19.039387+00:00 [queued]>
[2024-10-10 02:17:20,471] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.query_contract 2024-10-10T02:17:19.039387+00:00 [queued]>
[2024-10-10 02:17:20,471] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-10-10 02:17:20,471] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-10-10 02:17:20,472] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-10-10 02:17:20,480] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): query_contract> on 2024-10-10T02:17:19.039387+00:00
[2024-10-10 02:17:20,484] {standard_task_runner.py:52} INFO - Started process 61762 to run task
[2024-10-10 02:17:20,487] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mssql_dag', 'query_contract', '2024-10-10T02:17:19.039387+00:00', '--job-id', '240', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mssql_dag.py', '--cfg-path', '/tmp/tmpk1ra4eqh', '--error-file', '/tmp/tmpqsnudp_y']
[2024-10-10 02:17:20,490] {standard_task_runner.py:77} INFO - Job 240: Subtask query_contract
[2024-10-10 02:17:20,519] {logging_mixin.py:104} INFO - Running <TaskInstance: mssql_dag.query_contract 2024-10-10T02:17:19.039387+00:00 [running]> on host da843a407010
[2024-10-10 02:17:20,550] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mssql_dag
AIRFLOW_CTX_TASK_ID=query_contract
AIRFLOW_CTX_EXECUTION_DATE=2024-10-10T02:17:19.039387+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-10T02:17:19.039387+00:00
[2024-10-10 02:17:20,610] {python.py:151} INFO - Done. Returned value was:      PROM_MEMB_NO  ...                       POST_DATETIME
0              24  ...                                NULL
1              50  ...                                NULL
2             132  ...                                NULL
3             237  ...  Wed Dec 07 10:34:45 GMT+07:00 2022
4             280  ...                                NULL
..            ...  ...                                 ...
495           489  ...                                NULL
496           492  ...                                NULL
497           492  ...                                NULL
498           492  ...                                NULL
499           512  ...                                NULL

[500 rows x 51 columns]
[2024-10-10 02:17:20,658] {xcom.py:229} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2024-10-10 02:17:20,659] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1364, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1943, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/xcom.py", line 79, in set
    value = XCom.serialize_value(value)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/xcom.py", line 226, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2024-10-10 02:17:20,660] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=mssql_dag, task_id=query_contract, execution_date=20241010T021719, start_date=20241010T021720, end_date=20241010T021720
[2024-10-10 02:17:20,699] {local_task_job.py:149} INFO - Task exited with return code 1
