[2024-10-10 03:37:47,671] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.query_member 2024-10-10T03:37:46.554834+00:00 [queued]>
[2024-10-10 03:37:47,680] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.query_member 2024-10-10T03:37:46.554834+00:00 [queued]>
[2024-10-10 03:37:47,681] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-10-10 03:37:47,682] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-10-10 03:37:47,683] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-10-10 03:37:47,693] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): query_member> on 2024-10-10T03:37:46.554834+00:00
[2024-10-10 03:37:47,697] {standard_task_runner.py:52} INFO - Started process 4118 to run task
[2024-10-10 03:37:47,700] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mssql_dag', 'query_member', '2024-10-10T03:37:46.554834+00:00', '--job-id', '330', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mssql_dag.py', '--cfg-path', '/tmp/tmpqc7uhgsh', '--error-file', '/tmp/tmpxe1c8eg6']
[2024-10-10 03:37:47,703] {standard_task_runner.py:77} INFO - Job 330: Subtask query_member
[2024-10-10 03:37:47,734] {logging_mixin.py:104} INFO - Running <TaskInstance: mssql_dag.query_member 2024-10-10T03:37:46.554834+00:00 [running]> on host da843a407010
[2024-10-10 03:37:47,770] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mssql_dag
AIRFLOW_CTX_TASK_ID=query_member
AIRFLOW_CTX_EXECUTION_DATE=2024-10-10T03:37:46.554834+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-10T03:37:46.554834+00:00
[2024-10-10 03:37:47,902] {logging_mixin.py:104} INFO -      MAST_MEMB_NO MAST_MEMB_DEPT  ... MAST_GUIDE_MEMB_NO POST_DATETIME
0            44.0           1154  ...               NULL          NULL
1            48.0           1156  ...               NULL          NULL
2            49.0           1156  ...               NULL          NULL
3            50.0           1156  ...               NULL          NULL
4            56.0           1156  ...               NULL          NULL
..            ...            ...  ...                ...           ...
146         752.0           1156  ...               NULL          NULL
147         756.0           1156  ...               NULL          NULL
148         759.0           1156  ...               NULL          NULL
149         761.0           1155  ...               NULL          NULL
150         767.0           1156  ...               NULL          NULL

[151 rows x 85 columns]
[2024-10-10 03:37:47,926] {logging_mixin.py:104} INFO - All records deleted from table 'tmp_member' successfully.
[2024-10-10 03:37:48,154] {logging_mixin.py:104} INFO - Error inserting DataFrame: (207, b"Invalid column name 'nan'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[2024-10-10 03:37:48,154] {python.py:151} INFO - Done. Returned value was: None
[2024-10-10 03:37:48,162] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=mssql_dag, task_id=query_member, execution_date=20241010T033746, start_date=20241010T033747, end_date=20241010T033748
[2024-10-10 03:37:48,185] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-10 03:37:48,193] {local_task_job.py:149} INFO - Task exited with return code 0
